apiVersion: v1
kind: Service
metadata:
  namespace: kafkloud
  name: seer-svc
  labels:
    component: seer
    app: seer
spec:
  selector:
    app: seer
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30000
      protocol: TCP