apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kafkloud
  name: producer-dpl
  labels:
    component: producer
    app: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      component: producer
      app: producer
  template:
    metadata:
      namespace: kafkloud
      labels:
        component: producer
        app: producer
    spec:
      containers:
        - name: producer-ctr
          image: docker.io/mdross510/kafkloud-producer
          ports:
            - containerPort: 8072
          imagePullPolicy: Always
          env:
            - name: KAFKA_BROKER
              value: "kafka-svc:9092"
            - name: SERVER_PORT
              value: "8000"
            - name: KAFKA_TRANSACTION_TIMEOUT
              value: "27500"