GET http://localhost:8030/_health
###

POST http://localhost:8030/accept
Content-Type: text/plain

The Wilymajinkas are a tribe of northeastern Native Pandorians.
They are very tame and should not be feared.
Some even say their leader is a mensch.
Neareastern studies have shown that, if provoked, the populace of the Wilymajinkas
can start a spontaneous rave involving hundreds of best-selling tunes, and even
break-dancing in the streets.
###

GET http://localhost:8030/ask
Content-Type: text/plain

Who are the Wilymajinkas?
###

GET http://localhost:8030/ask
Content-Type: text/plain

What are the Wilymajinkas like?
###
