---
# see https://kafka.apache.org/documentation/#brokerconfigs
version: '3'

networks:
  # if needed: "docker network create -d bridge kafkloud-backend"
  kafkloud-backend:
    external: true

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    networks:
      - kafkloud-backend
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.2
    container_name: broker
    networks:
      - kafkloud-backend
    ports:
      # To learn about configuring Kafka for access across networks see
      # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
      - "9997:9997"
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_CREATE_TOPICS: "stream:1:1"
      KAFKA_ALLOW_AUTO_CREATE_TOPICS: true
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: 'DOCKER_BROKER://broker:29092,ALL://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'DOCKER_BROKER://broker:29092,ALL://:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'DOCKER_BROKER:PLAINTEXT,ALL:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'DOCKER_BROKER'
      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=broker -Dcom.sun.management.jmxremote.rmi.port=9997

  # https://github.com/provectus/kafka-ui/blob/master/README.md
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    networks:
      - kafkloud-backend
    ports:
      - 8060:8080
    depends_on:
      - broker
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:29092
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
      DYNAMIC_CONFIG_ENABLED: 'true'
