apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kafkloud
  name: portal-dpl
  labels:
    component: portal
    app: portal
spec:
  replicas: 1
  selector:
    matchLabels:
      component: portal
      app: portal
  template:
    metadata:
      namespace: kafkloud
      labels:
        component: portal
        app: portal
    spec:
      containers:
      - name: portal-ctr
        image: docker.io/mdross510/kafkloud-portal
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
        env:
          - name: NODE_ENV
            value: "production"
