apiVersion: v1
kind: Service
metadata:
  namespace: kafkloud
  name: portal-svc
  labels:
    component: portal
    app: portal
spec:
  type: NodePort
  selector:
    component: portal
    app: portal
  ports:
    - port: 3000
      nodePort: 30080
      protocol: TCP