version: '3.9'

networks:
  # if needed: "docker network create -d bridge kafkloud-backend"
  kafkloud-backend:
    external: true

volumes:
  clickhouse_data:
    driver: local
  index_data:
    driver: local
  backups:
    driver: local

services:
  seer:
    image: docker.io/mdross510/kafkloud-seer
    container_name: seer
    networks:
      - kafkloud-backend
    depends_on:
      - chromadb
    ports:
      - 8030:8030
    environment:
      - KAFKA_BROKER=broker:9092
      - CHROMA_DB=chromadb:8000
      - OPENAI_API_KEY
  chromadb:
    image: ghcr.io/chroma-core/chroma:0.3.26
    container_name: chromadb
    networks:
      - kafkloud-backend
    volumes:
      - index_data:/index_data
    # the following 'command' entry should not be necessary; is here only because of the 'ERROR: Failed building wheel for hnswlib' issue
    command: uvicorn chromadb.app:app --reload --workers 1 --host 0.0.0.0 --port 8000 --log-config log_config.yml
    environment:
      - CHROMA_DB_IMPL=clickhouse
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
      - HNSWLIB_NO_NATIVE=1
    ports:
      - 8000:8000
    depends_on:
      - clickhouse

  clickhouse:
    image: clickhouse/clickhouse-server:22.9-alpine
    container_name: clickhouse
    networks:
      - kafkloud-backend
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - CLICKHOUSE_TCP_PORT=9000
      - CLICKHOUSE_HTTP_PORT=8123
    ports:
      - '8123:8123'
      - '9000:9000'
    volumes:
      - clickhouse_data:/bitnami/clickhouse
      - backups:/backups
      - ./config/backup_disk.xml:/etc/clickhouse-server/config.d/backup_disk.xml
      - ./config/chroma_users.xml:/etc/clickhouse-server/users.d/chroma.xml
