FROM node:18-alpine AS base

FROM base AS deps
# See https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm ci

FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ENV NEXT_TELEMETRY_DISABLED 1

RUN npm run build

FROM base AS runner
WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public

# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

COPY --from=builder --chown=nextjs:nodejs /app/env-launcher.sh .
RUN touch .env.local
RUN chown nextjs:nodejs .env.local


USER nextjs

EXPOSE 3000

ENV PORT 3000

CMD ["/bin/sh", "./env-launcher.sh", ".env.local", "HOSTNAME NODE_ENV NEXT_PUBLIC_CONSUMER_ADDR NEXT_PUBLIC_PRODUCER_ADDR" , "exec", "node", "server.js"]