apiVersion: v1
kind: Service
metadata:
  namespace: kafkloud
  name: consumer-svc
  labels:
    component: consumer
    app: consumer
spec:
  type: NodePort
  selector:
    component: consumer
    app: consumer
  ports:
  - port: 8072
    targetPort: 8072
    nodePort: 30072
    protocol: TCP